version: '3.8'

services:
  zuzzuu-web:
    image: nginx:alpine
    container_name: zuzzuu-website
    ports:
      - "3000:3000" # Expose port 3000
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - zuzzuu-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: zuzzuu-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - zuzzuu-network

networks:
  zuzzuu-network:
    driver: bridge