version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    volumes:
      - .:/app       # Mount current directory for live reload in development
      - /app/node_modules # Avoid mounting node_modules to prevent conflicts
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
