version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
